/* eslint-disable import/prefer-default-export */
export const tableData = [
    {
        "id": "1",
        "date": "Sunday, September 6, 2020",
        "time": "12:00",
        "type": "YouTube Live",
        "name": "Course overview",
        "descriptionUrl": "https://youtu.be/u5edb5GVIHY",
        "description": "Stage#1 Intro",
        "comment": "Дмитрий Воробей, Сергей Шаляпин",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "dateTime": "2020-09-06 12:00:00"
    },
    {
        "id": "2",
        "date": "Sunday, September 6, 2020",
        "time": "12:00",
        "type": "YouTube Live",
        "name": "https://www.youtube.com/rollingscopesschool",
        "descriptionUrl": "https://www.youtube.com/rollingscopesschool",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "dateTime": "2020-09-06 12:00:00"
    },
    {
        "id": "3",
        "date": "Sunday, September 6, 2020",
        "time": "12:00",
        "type": "Выдача таска",
        "name": "HTML для начинающих",
        "descriptionUrl": "https://ru.code-basics.com/languages/html",
        "timeToComplete": "8h",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "dateTime": "2020-09-06 12:00:00"
    },
    {
        "id": "4",
        "date": "Sunday, September 6, 2020",
        "time": "12:00",
        "type": "Выдача таска",
        "name": "CSS для начинающих",
        "descriptionUrl": "https://ru.code-basics.com/languages/css",
        "timeToComplete": "8h",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "dateTime": "2020-09-06 12:00:00"
    },
    {
        "id": "5",
        "date": "Sunday, September 6, 2020",
        "time": "12:00",
        "type": "Выдача таска",
        "name": "JavaScript для начинающих",
        "descriptionUrl": "https://ru.code-basics.com/languages/javascript",
        "timeToComplete": "20h",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "dateTime": "2020-09-06 12:00:00"
    },
    {
        "id": "6",
        "date": "Sunday, September 6, 2020",
        "time": "12:00",
        "type": "Self education",
        "name": "Browsers and IDEs",
        "descriptionUrl": "https://www.youtube.com/watch?v=nd2VYxOsOwY&t=",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "dateTime": "2020-09-06 12:00:00"
    },
    {
        "id": "7",
        "date": "Sunday, September 6, 2020",
        "time": "12:00",
        "type": "Self education",
        "name": "HTML and CSS Basics",
        "descriptionUrl": "https://youtu.be/2iCgf03rx1I",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "dateTime": "2020-09-06 12:00:00"
    },
    {
        "id": "8",
        "date": "Sunday, September 6, 2020",
        "time": "12:00",
        "type": "Self education",
        "name": "HTML & CSS - Building first simple page",
        "descriptionUrl": "https://youtu.be/B0RuI1L5r9Q",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "dateTime": "2020-09-06 12:00:00"
    },
    {
        "id": "9",
        "date": "Tuesday, September 8, 2020",
        "time": "19:00",
        "type": "YouTube Live",
        "name": "Профориентация",
        "descriptionUrl": "https://www.youtube.com/watch?v=pQ0hr5U8RL0",
        "comment": "RSSchool Crew",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "dateTime": "2020-09-08 19:00:00"
    },
    {
        "id": "10",
        "date": "Saturday, September 12, 2020",
        "time": "19:00",
        "type": "YouTube Live ",
        "name": "https://www.youtube.com/c/Luffi2539/live",
        "descriptionUrl": "https://www.youtube.com/c/Luffi2539/live",
        "comment": "Виктор Ковалев",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "dateTime": "2020-09-12 19:00:00"
    },
]