/* eslint-disable import/prefer-default-export */
export const someData = [
    {
        "id": "1",
        "date": "Wednesday, January 1, 2020",
        "time": "12:00:00 AM",
        "dateTime": "2020-01-01 0:00:00",
        "blockName": "Computer Science Basics",
        "name": "Computer Science Basics",
        "timeToComplete": "16h",
        "description": "Пройти этот курс рекомендует EPAM. Из описания: Данный тренинг может быть хорошим стартом для дальнейшего изучения программирования и инженерной работы в IT сфере. На странице курса все темы отмечены галочками.\r\nСтудент может пояснить решение алгоритмов раздела  Data Types and Algoritms задание Test - operators",
        "comment": "Курс проходится за полчаса кликами по кнопке Next и перебором вариантов ответа в тестах. ",
        "descriptionUrl": "http://epa.ms/upskill-start",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "2",
        "date": "Thursday, January 2, 2020",
        "time": "1:00:00 AM",
        "dateTime": "2020-01-02 1:00:00",
        "blockName": "HTML/Css online resource",
        "name": "HTML/Css online resource",
        "timeToComplete": "16h",
        "description": "Базовый курс по html / css На странице курса все темы отмечены галочками. Студент может пояснить решение некоторых заданий (на выбор ментора)",
        "comment": "Решения всех заданий доступны после 20-минутной паузы. Для проверки самостоятельности решения  заданий нужно посмотреть и послушать как студент решает пройденные им таски",
        "descriptionUrl": "HTML/Css online resource \r\nhttps://ru.code-basics.com/languages/html\r\nhttps://ru.code-basics.com/languages/css",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "3",
        "date": "Friday, January 3, 2020",
        "time": "2:00:00 AM",
        "dateTime": "2020-01-03 2:00:00",
        "blockName": "JS online resource",
        "name": "JS online resource",
        "description": "Базовый курс JavaScript. Если проходить осмысленно, даст неплохое представление о языке и его возможностях. ",
        "comment": "Решения всех заданий доступны после 20-минутной паузы. Для проверки самостоятельности решения  заданий нужно посмотреть и послушать как студент решает пройденные им таски",
        "descriptionUrl": "https://ru.code-basics.com/languages/javascript",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "4",
        "date": "Saturday, January 4, 2020",
        "time": "3:00:00 AM",
        "dateTime": "2020-01-04 3:00:00",
        "blockName": "Git & GitHub\r\n",
        "name": "Регистрация на Гитхабе",
        "timeToComplete": "0.5h",
        "description": "Установлен Git\r\nСоздан github-аккаунт ",
        "comment": "-",
        "descriptionUrl": "https://htmlacademy.ru/blog/boost/tools/register-on-github-work-with-console",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "5",
        "date": "Sunday, January 5, 2020",
        "time": "4:00:00 AM",
        "dateTime": "2020-01-05 4:00:00",
        "blockName": "Git & GitHub\r\n",
        "name": "Полезные команды для работы с Git",
        "timeToComplete": "0.5h",
        "description": "Создан репозиторий на гитхабе, создана ветка, добавлены файлы ",
        "comment": "-",
        "descriptionUrl": "https://htmlacademy.ru/blog/boost/tools/useful-commands-for-working-with-git",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "6",
        "date": "Monday, January 6, 2020",
        "time": "5:00:00 AM",
        "dateTime": "2020-01-06 5:00:00",
        "blockName": "Git & GitHub\r\n",
        "name": "Требования к именам коммитов",
        "timeToComplete": "0.5h",
        "description": "Студент даёт имена коммитам согласно гайдлайну",
        "comment": "-",
        "descriptionUrl": "https://docs.rs.school/#/git-convention",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "7",
        "date": "Tuesday, January 7, 2020",
        "time": "6:00:00 AM",
        "dateTime": "2020-01-07 6:00:00",
        "blockName": "Git & GitHub\r\n",
        "name": "Как разместить приложение на  GitHub Pages",
        "timeToComplete": "0.5h",
        "description": "Студент использует GitHub Pages и Netlify для деплоя своих проектов",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/create-github-pages.md",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "8",
        "date": "Wednesday, January 8, 2020",
        "time": "7:00:00 AM",
        "dateTime": "2020-01-08 7:00:00",
        "blockName": "IDE",
        "name": "VS Code – установка и настройка",
        "timeToComplete": "1h",
        "description": "Установлен Visual Studio Code и рекомендованные плагины, студент может написать код в редакторе, ",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/5M6RL3MAGJU",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "9",
        "date": "Thursday, January 9, 2020",
        "time": "8:00:00 AM",
        "dateTime": "2020-01-09 8:00:00",
        "blockName": "IDE",
        "name": "Как написать и запустить HTML на компьютере?",
        "timeToComplete": "0.5h",
        "description": "Студент может открыть html код в браузере используя плагин  LiveServer",
        "comment": "-",
        "descriptionUrl": "https://htmlacademy.ru/blog/education/all/how-to-run-html",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "10",
        "date": "Friday, January 10, 2020",
        "time": "9:00:00 AM",
        "dateTime": "2020-01-10 9:00:00",
        "blockName": "Markdown",
        "name": "Что такое Markdown",
        "timeToComplete": "0.5h",
        "description": "Студент знаком с синтаксисом Markdown и может его применить",
        "comment": "-",
        "descriptionUrl": "https://guides.hexlet.io/markdown/",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
]