/* eslint-disable import/prefer-default-export */
// export const tableData = [
//     {
//         "id": "1",
//         "date": "Sunday, September 6, 2020",
//         "time": "12:00",
//         "type": "YouTube Live",
//         "name": "Course overview",
//         "descriptionUrl": "https://youtu.be/u5edb5GVIHY",
//         "description": "Stage#1 Intro",
//         "comment": "Дмитрий Воробей, Сергей Шаляпин",
//         "timeZone": "UTC +3 MSK Minsk",
//         "place": "online",
//         "dateTime": "2020-09-06 12:00:00"
//     },
//     {
//         "id": "2",
//         "date": "Sunday, September 6, 2020",
//         "time": "12:00",
//         "type": "YouTube Live",
//         "name": "https://www.youtube.com/rollingscopesschool",
//         "descriptionUrl": "https://www.youtube.com/rollingscopesschool",
//         "timeZone": "UTC +3 MSK Minsk",
//         "place": "online",
//         "dateTime": "2020-09-06 12:00:00"
//     },
//     {
//         "id": "3",
//         "date": "Sunday, September 6, 2020",
//         "time": "12:00",
//         "type": "Выдача таска",
//         "name": "HTML для начинающих",
//         "descriptionUrl": "https://ru.code-basics.com/languages/html",
//         "timeToComplete": "8h",
//         "timeZone": "UTC +3 MSK Minsk",
//         "place": "online",
//         "dateTime": "2020-09-06 12:00:00"
//     },
//     {
//         "id": "4",
//         "date": "Sunday, September 6, 2020",
//         "time": "12:00",
//         "type": "Выдача таска",
//         "name": "CSS для начинающих",
//         "descriptionUrl": "https://ru.code-basics.com/languages/css",
//         "timeToComplete": "8h",
//         "timeZone": "UTC +3 MSK Minsk",
//         "place": "online",
//         "dateTime": "2020-09-06 12:00:00"
//     },
//     {
//         "id": "5",
//         "date": "Sunday, September 6, 2020",
//         "time": "12:00",
//         "type": "Выдача таска",
//         "name": "JavaScript для начинающих",
//         "descriptionUrl": "https://ru.code-basics.com/languages/javascript",
//         "timeToComplete": "20h",
//         "timeZone": "UTC +3 MSK Minsk",
//         "place": "online",
//         "dateTime": "2020-09-06 12:00:00"
//     },
//     {
//         "id": "6",
//         "date": "Sunday, September 6, 2020",
//         "time": "12:00",
//         "type": "Self education",
//         "name": "Browsers and IDEs",
//         "descriptionUrl": "https://www.youtube.com/watch?v=nd2VYxOsOwY&t=",
//         "timeZone": "UTC +3 MSK Minsk",
//         "place": "online",
//         "dateTime": "2020-09-06 12:00:00"
//     },
//     {
//         "id": "7",
//         "date": "Sunday, September 6, 2020",
//         "time": "12:00",
//         "type": "Self education",
//         "name": "HTML and CSS Basics",
//         "descriptionUrl": "https://youtu.be/2iCgf03rx1I",
//         "timeZone": "UTC +3 MSK Minsk",
//         "place": "online",
//         "dateTime": "2020-09-06 12:00:00"
//     },
//     {
//         "id": "8",
//         "date": "Sunday, September 6, 2020",
//         "time": "12:00",
//         "type": "Self education",
//         "name": "HTML & CSS - Building first simple page",
//         "descriptionUrl": "https://youtu.be/B0RuI1L5r9Q",
//         "timeZone": "UTC +3 MSK Minsk",
//         "place": "online",
//         "dateTime": "2020-09-06 12:00:00"
//     },
//     {
//         "id": "9",
//         "date": "Tuesday, September 8, 2020",
//         "time": "19:00",
//         "type": "YouTube Live",
//         "name": "Профориентация",
//         "descriptionUrl": "https://www.youtube.com/watch?v=pQ0hr5U8RL0",
//         "comment": "RSSchool Crew",
//         "timeZone": "UTC +3 MSK Minsk",
//         "place": "online",
//         "dateTime": "2020-09-08 19:00:00"
//     },
//     {
//         "id": "10",
//         "date": "Saturday, September 12, 2020",
//         "time": "19:00",
//         "type": "YouTube Live ",
//         "name": "https://www.youtube.com/c/Luffi2539/live",
//         "descriptionUrl": "https://www.youtube.com/c/Luffi2539/live",
//         "comment": "Виктор Ковалев",
//         "timeZone": "UTC +3 MSK Minsk",
//         "place": "online",
//         "dateTime": "2020-09-12 19:00:00"
//     },
// ]






export const tableData = [
    {
        "id": "1",
        "date": "Wednesday, January 1, 2020",
        "time": "12:00:00 AM",
        "dateTime": "2020-01-01 0:00:00",
        "blockName": "Computer Science Basics",
        "name": "Computer Science Basics",
        "timeToComplete": "16h",
        "description": "Пройти этот курс рекомендует EPAM. Из описания: Данный тренинг может быть хорошим стартом для дальнейшего изучения программирования и инженерной работы в IT сфере. На странице курса все темы отмечены галочками.\r\nСтудент может пояснить решение алгоритмов раздела  Data Types and Algoritms задание Test - operators",
        "comment": "Курс проходится за полчаса кликами по кнопке Next и перебором вариантов ответа в тестах. ",
        "descriptionUrl": "http://epa.ms/upskill-start",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "2",
        "date": "Thursday, January 2, 2020",
        "time": "1:00:00 AM",
        "dateTime": "2020-01-02 1:00:00",
        "blockName": "HTML/Css online resource",
        "name": "HTML/Css online resource",
        "timeToComplete": "16h",
        "description": "Базовый курс по html / css На странице курса все темы отмечены галочками. Студент может пояснить решение некоторых заданий (на выбор ментора)",
        "comment": "Решения всех заданий доступны после 20-минутной паузы. Для проверки самостоятельности решения  заданий нужно посмотреть и послушать как студент решает пройденные им таски",
        "descriptionUrl": "HTML/Css online resource \r\nhttps://ru.code-basics.com/languages/html\r\nhttps://ru.code-basics.com/languages/css",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "3",
        "date": "Friday, January 3, 2020",
        "time": "2:00:00 AM",
        "dateTime": "2020-01-03 2:00:00",
        "blockName": "JS online resource",
        "name": "JS online resource",
        "description": "Базовый курс JavaScript. Если проходить осмысленно, даст неплохое представление о языке и его возможностях. ",
        "comment": "Решения всех заданий доступны после 20-минутной паузы. Для проверки самостоятельности решения  заданий нужно посмотреть и послушать как студент решает пройденные им таски",
        "descriptionUrl": "https://ru.code-basics.com/languages/javascript",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "4",
        "date": "Saturday, January 4, 2020",
        "time": "3:00:00 AM",
        "dateTime": "2020-01-04 3:00:00",
        "blockName": "Git & GitHub\r\n",
        "name": "Регистрация на Гитхабе",
        "timeToComplete": "0.5h",
        "description": "Установлен Git\r\nСоздан github-аккаунт ",
        "comment": "-",
        "descriptionUrl": "https://htmlacademy.ru/blog/boost/tools/register-on-github-work-with-console",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "5",
        "date": "Sunday, January 5, 2020",
        "time": "4:00:00 AM",
        "dateTime": "2020-01-05 4:00:00",
        "blockName": "Git & GitHub\r\n",
        "name": "Полезные команды для работы с Git",
        "timeToComplete": "0.5h",
        "description": "Создан репозиторий на гитхабе, создана ветка, добавлены файлы ",
        "comment": "-",
        "descriptionUrl": "https://htmlacademy.ru/blog/boost/tools/useful-commands-for-working-with-git",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "6",
        "date": "Monday, January 6, 2020",
        "time": "5:00:00 AM",
        "dateTime": "2020-01-06 5:00:00",
        "blockName": "Git & GitHub\r\n",
        "name": "Требования к именам коммитов",
        "timeToComplete": "0.5h",
        "description": "Студент даёт имена коммитам согласно гайдлайну",
        "comment": "-",
        "descriptionUrl": "https://docs.rs.school/#/git-convention",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "7",
        "date": "Tuesday, January 7, 2020",
        "time": "6:00:00 AM",
        "dateTime": "2020-01-07 6:00:00",
        "blockName": "Git & GitHub\r\n",
        "name": "Как разместить приложение на  GitHub Pages",
        "timeToComplete": "0.5h",
        "description": "Студент использует GitHub Pages и Netlify для деплоя своих проектов",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/create-github-pages.md",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "8",
        "date": "Wednesday, January 8, 2020",
        "time": "7:00:00 AM",
        "dateTime": "2020-01-08 7:00:00",
        "blockName": "IDE",
        "name": "VS Code – установка и настройка",
        "timeToComplete": "1h",
        "description": "Установлен Visual Studio Code и рекомендованные плагины, студент может написать код в редакторе, ",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/5M6RL3MAGJU",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "9",
        "date": "Thursday, January 9, 2020",
        "time": "8:00:00 AM",
        "dateTime": "2020-01-09 8:00:00",
        "blockName": "IDE",
        "name": "Как написать и запустить HTML на компьютере?",
        "timeToComplete": "0.5h",
        "description": "Студент может открыть html код в браузере используя плагин  LiveServer",
        "comment": "-",
        "descriptionUrl": "https://htmlacademy.ru/blog/education/all/how-to-run-html",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "10",
        "date": "Friday, January 10, 2020",
        "time": "9:00:00 AM",
        "dateTime": "2020-01-10 9:00:00",
        "blockName": "Markdown",
        "name": "Что такое Markdown",
        "timeToComplete": "0.5h",
        "description": "Студент знаком с синтаксисом Markdown и может его применить",
        "comment": "-",
        "descriptionUrl": "https://guides.hexlet.io/markdown/",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "11",
        "date": "Saturday, January 11, 2020",
        "time": "10:00:00 AM",
        "dateTime": "2020-01-11 10:00:00",
        "blockName": "Практика.",
        "name": "Task Markdown & Git",
        "timeToComplete": "4h",
        "description": "Создан и размещён на gh-pages файл cv md с cv студента",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/git-markdown.md",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "12",
        "date": "Sunday, January 12, 2020",
        "time": "11:00:00 AM",
        "dateTime": "2020-01-12 11:00:00",
        "blockName": "HTML/Css Basic. Semantic. ",
        "name": "HTML для самых маленьких",
        "timeToComplete": "2.5h",
        "description": "Плейлист от Glo Academy с разбором особенностей HTML",
        "comment": "-",
        "descriptionUrl": "https://www.youtube.com/playlist?list=PL3LQJkGQtzc7aWRyr-GaxyO_dwj5inJ1t",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "13",
        "date": "Monday, January 13, 2020",
        "time": "12:00:00 PM",
        "dateTime": "2020-01-13 12:00:00",
        "blockName": "HTML/Css Basic. Semantic. ",
        "name": "HTML для начинающих",
        "timeToComplete": "2.5h",
        "description": "Плейлист от loftblog с отличным понятным доступным объяснением",
        "comment": "-",
        "descriptionUrl": "https://www.youtube.com/playlist?list=PLY4rE9dstrJyeZlPWoKJr1xKVVnG4w-Hc",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "14",
        "date": "Tuesday, January 14, 2020",
        "time": "1:00:00 PM",
        "dateTime": "2020-01-14 13:00:00",
        "blockName": "HTML/Css Basic. Semantic. ",
        "name": "Справочник EMMET сокращений для ускорения верстки",
        "timeToComplete": "0.5h",
        "description": "Студент знает и использует в вёрстке некоторые сокращения emmet ",
        "comment": "-",
        "descriptionUrl": "https://webdesign-master.ru/blog/html-css/2.html",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "15",
        "date": "Wednesday, January 15, 2020",
        "time": "2:00:00 PM",
        "dateTime": "2020-01-15 14:00:00",
        "blockName": "HTML/Css Basic. Semantic. ",
        "name": "Плагин Emmet - обзор",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://www.youtube.com/watch?v=WeNN9So5DTs",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "16",
        "date": "Thursday, January 16, 2020",
        "time": "3:00:00 PM",
        "dateTime": "2020-01-16 15:00:00",
        "blockName": "HTML/Css Basic. Semantic. ",
        "name": "Семантические теги в HTML",
        "timeToComplete": "0.5h",
        "description": "Студент знает и использует в вёрстке семантические теги",
        "comment": "-",
        "descriptionUrl": "https://www.youtube.com/watch?v=bQRmGxhARhc",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "17",
        "date": "Friday, January 17, 2020",
        "time": "4:00:00 PM",
        "dateTime": "2020-01-17 16:00:00",
        "blockName": "HTML/Css Basic. Semantic. ",
        "name": "HTML5 Семантические элементы",
        "timeToComplete": "0.5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://html5css.ru/html/html5_semantic_elements.php",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "18",
        "date": "Saturday, January 18, 2020",
        "time": "5:00:00 PM",
        "dateTime": "2020-01-18 17:00:00",
        "blockName": "Практика.",
        "name": "Task HTML, CSS & Git Basics",
        "timeToComplete": "2h",
        "description": "Вёрстка cv студента на основе markdown файла из таска Markdown & Git. Создан файл index.html. Студент использует в вёрстке семантические теги",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codejam-cv.md",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "19",
        "date": "Sunday, January 19, 2020",
        "time": "6:00:00 PM",
        "dateTime": "2020-01-19 18:00:00",
        "blockName": "CSS3.",
        "name": "Видео лекция HTML/Css Basic",
        "timeToComplete": "2.5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://www.youtube.com/watch?v=xdBTX4RMoBE&list=PLe--kalBDwji8WXKVjhON39X4v_Uj6T_R&index=2",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "20",
        "date": "Monday, January 20, 2020",
        "time": "7:00:00 PM",
        "dateTime": "2020-01-20 19:00:00",
        "blockName": "CSS3.",
        "name": "CSS для самых маленьких",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://www.youtube.com/playlist?list=PL3LQJkGQtzc6_KA1AZy9O6kVWwX1hoaTn",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "21",
        "date": "Tuesday, January 21, 2020",
        "time": "8:00:00 PM",
        "dateTime": "2020-01-21 20:00:00",
        "blockName": "CSS3.",
        "name": "30 CSS-селекторов, которые вы должны знать",
        "timeToComplete": "0.5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "http://rightblog.ru/2606",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "22",
        "date": "Wednesday, January 22, 2020",
        "time": "9:00:00 PM",
        "dateTime": "2020-01-22 21:00:00",
        "blockName": "Практика",
        "name": "Изучение селекторов посредством игры",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://flukeout.github.io/",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "23",
        "date": "Thursday, January 23, 2020",
        "time": "10:00:00 PM",
        "dateTime": "2020-01-23 22:00:00",
        "blockName": "Практика",
        "name": "Task HTML, CSS & Git Basics",
        "timeToComplete": "2h",
        "description": "Стилизация cv студента на основе созданного index.html файла        Пример оформления (optional)",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codejam-cv.md",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "24",
        "date": "Friday, January 24, 2020",
        "time": "11:00:00 PM",
        "dateTime": "2020-01-24 23:00:00",
        "blockName": "Практика",
        "name": "Build a Tribute Page",
        "timeToComplete": "4h",
        "description": " Очень базовый и простой макет.",
        "comment": "-",
        "descriptionUrl": "https://www.freecodecamp.org/learn/responsive-web-design/responsive-web-design-projects/build-a-tribute-page",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "25",
        "date": "Saturday, January 25, 2020",
        "time": "12:00:00 AM",
        "dateTime": "2020-01-26 0:00:00",
        "blockName": "CSS positioning and layout (Flex)",
        "name": "Видео лекция Position. Floats. Flex. Semantic. CSS3",
        "timeToComplete": "2h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://www.youtube.com/watch?v=iSQcOjxttNg&list=PLe--kalBDwji8WXKVjhON39X4v_Uj6T_R&index=3",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "26",
        "date": "Sunday, January 26, 2020",
        "time": "1:00:00 AM",
        "dateTime": "2020-01-27 1:00:00",
        "blockName": "CSS positioning and layout (Flex)",
        "name": "CSS: Flexbox",
        "timeToComplete": "0.5h",
        "description": "Студент знает особенности вёрстки на флексбоксах\r\n",
        "comment": "-",
        "descriptionUrl": "https://www.evernote.com/shard/s368/client/snv?noteGuid=4346cdea-9386-4738-bfff-f9faafc05e94&noteKey=fb6ec76312f7111b&sn=https%3A%2F%2Fwww.evernote.com%2Fshard%2Fs368%2Fsh%2F4346cdea-9386-4738-bfff-f9faafc05e94%2Ffb6ec76312f7111b&title=CSS%253A%2BFlexbox%2B%2528htmlacademy.ru%2529",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "27",
        "date": "Monday, January 27, 2020",
        "time": "2:00:00 AM",
        "dateTime": "2020-01-28 2:00:00",
        "blockName": "CSS positioning and layout (Flex)",
        "name": "Шпаргалка по Flexbox",
        "timeToComplete": "0.5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://habr.com/ru/post/313938/",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "28",
        "date": "Tuesday, January 28, 2020",
        "time": "3:00:00 AM",
        "dateTime": "2020-01-29 3:00:00",
        "blockName": "Практика",
        "name": "Task HTML, CSS & Git Basics",
        "timeToComplete": "2h",
        "description": "Завершение стилизации cv студента на основе созданного index.html файла. ",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codejam-cv.md",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "29",
        "date": "Wednesday, January 29, 2020",
        "time": "4:00:00 AM",
        "dateTime": "2020-01-30 4:00:00",
        "blockName": "Практика",
        "name": "Изучение флексбоксов посредством игры",
        "timeToComplete": "1h",
        "description": "Студент использует флексбоксы для решения поставленных задач",
        "comment": "-",
        "descriptionUrl": "https://flexboxfroggy.com/#ru",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "30",
        "date": "Thursday, January 30, 2020",
        "time": "5:00:00 AM",
        "dateTime": "2020-01-31 5:00:00",
        "blockName": "Практика",
        "name": "CSS3-медиазапросы",
        "timeToComplete": "0.5h",
        "description": "Студент имеет представление про медиазапросы",
        "comment": "-",
        "descriptionUrl": "https://html5book.ru/css3-mediazaprosy/",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "31",
        "date": "Friday, January 31, 2020",
        "time": "6:00:00 AM",
        "dateTime": "2020-02-01 6:00:00",
        "blockName": "Практика",
        "name": "Уроки CSS - Медиа запросы основы",
        "timeToComplete": "0.5h",
        "description": "Студент знает как использовать медиазапросы",
        "comment": "-",
        "descriptionUrl": "https://www.youtube.com/watch?v=M-xc1EOMOIE",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "32",
        "date": "Saturday, February 1, 2020",
        "time": "7:00:00 AM",
        "dateTime": "2020-02-02 7:00:00",
        "blockName": "Практика",
        "name": "Task HTML, CSS & Git Basics. ",
        "timeToComplete": "3h",
        "description": "Адаптивный дизайн cv с использованием медиазапросов",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codejam-cv.md",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "33",
        "date": "Sunday, February 2, 2020",
        "time": "8:00:00 AM",
        "dateTime": "2020-02-03 8:00:00",
        "blockName": "Git & GitHub\r\n",
        "name": "Конспект",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://www.evernote.com/l/AXCxNZiDK55Bmrne3ZWfwF8Fl8DxlIbYUbM/",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "34",
        "date": "Monday, February 3, 2020",
        "time": "9:00:00 AM",
        "dateTime": "2020-02-04 9:00:00",
        "blockName": "Git & GitHub\r\n",
        "name": "Интерактивный курс ",
        "timeToComplete": "1,5h",
        "description": "Интерактивный курс по Git",
        "comment": "-",
        "descriptionUrl": "https://learngitbranching.js.org/",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "35",
        "date": "Tuesday, February 4, 2020",
        "time": "10:00:00 AM",
        "dateTime": "2020-02-05 10:00:00",
        "blockName": "Chrome DevTools",
        "name": "Видео лекция по дев тулам ",
        "timeToComplete": "1,5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://www.youtube.com/watch?v=gvB0qoio-Ic&list=PLe--kalBDwji8WXKVjhON39X4v_Uj6T_R&index=7",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "36",
        "date": "Wednesday, February 5, 2020",
        "time": "11:00:00 AM",
        "dateTime": "2020-02-06 11:00:00",
        "blockName": "Chrome DevTools",
        "name": "Основы CSS/CSS3",
        "timeToComplete": "5h",
        "description": "плейлист от Sorax - 23 видео по CSS3",
        "comment": "-",
        "descriptionUrl": "https://www.youtube.com/playlist?list=PL026CCEB5125879C2",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "37",
        "date": "Thursday, February 6, 2020",
        "time": "12:00:00 PM",
        "dateTime": "2020-02-07 12:00:00",
        "blockName": "Chrome DevTools",
        "name": "Stream 11.02.2020",
        "timeToComplete": "1,5h",
        "description": "Вебинар Сергея Шаляпина\r\nFAQ Broswers and IDEs FAQ HTML and CSS Basics",
        "comment": "-",
        "descriptionUrl": "https://www.youtube.com/watch?v=UQavTWiTpnA",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "38",
        "date": "Friday, February 7, 2020",
        "time": "1:00:00 PM",
        "dateTime": "2020-02-08 13:00:00",
        "blockName": "Chrome DevTools",
        "name": "Stream 03.03.2020",
        "timeToComplete": "2,5h",
        "description": "вебинар Сергея Шаляпина\r\nForms & Inputs. Flexbox & Grid example. Singolo 1 review.",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/PhRVJC0kBGE",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "39",
        "date": "Saturday, February 8, 2020",
        "time": "2:00:00 PM",
        "dateTime": "2020-02-09 14:00:00",
        "blockName": "Chrome DevTools",
        "name": "Stream 10.03.2020",
        "timeToComplete": "2,5h",
        "description": "вебинар Сергея Шаляпина\r\nDOM events exampes. Singolo 3 review",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/_5f0kznOM_A",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "40",
        "date": "Sunday, February 9, 2020",
        "time": "3:00:00 PM",
        "dateTime": "2020-02-10 15:00:00",
        "blockName": "Chrome DevTools",
        "name": "Stream 17.03.2020",
        "timeToComplete": "2h",
        "description": "вебинар Сергея Шаляпина\r\nDOM examples. Singolo DOM FAQ.  Singolo responsive details.",
        "comment": "-",
        "descriptionUrl": "https://www.youtube.com/watch?v=0M9Rz-wXYas",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "41",
        "date": "Monday, February 10, 2020",
        "time": "4:00:00 PM",
        "dateTime": "2020-02-11 16:00:00",
        "blockName": "Chrome DevTools",
        "name": "Stream 26.03.2020",
        "timeToComplete": "1,5h",
        "description": "вебинар Сергея Шаляпина\r\nSingolo FAQ",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/fFDw7AH2OXo",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "42",
        "date": "Tuesday, February 11, 2020",
        "time": "5:00:00 PM",
        "dateTime": "2020-02-12 17:00:00",
        "blockName": "Chrome DevTools",
        "name": "Friday Live Coding. Part 1",
        "timeToComplete": "2,5h",
        "description": "вебинар Виктории Ворожун",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/ZAde-IJAHzo",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "43",
        "date": "Wednesday, February 12, 2020",
        "time": "6:00:00 PM",
        "dateTime": "2020-02-13 18:00:00",
        "blockName": "Chrome DevTools",
        "name": "Friday Live Coding. Part 2",
        "timeToComplete": "2,5h",
        "description": "вебинар Виктории Ворожун",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/BJENQIX2e2o",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "44",
        "date": "Thursday, February 13, 2020",
        "time": "7:00:00 PM",
        "dateTime": "2020-02-14 19:00:00",
        "blockName": "Chrome DevTools",
        "name": "Friday Live Coding. Part 3",
        "timeToComplete": "3h",
        "description": "вебинар Виктории Ворожун\r\nBase stylization using SASS for HTML BEM Markup",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/fooyYgIuZe8",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "45",
        "date": "Friday, February 14, 2020",
        "time": "8:00:00 PM",
        "dateTime": "2020-02-15 20:00:00",
        "blockName": "Chrome DevTools",
        "name": "Friday Live Coding. Part 4",
        "timeToComplete": "3h",
        "description": "вебинар Виктории Ворожун\r\nFAQ SASS. Media query.",
        "comment": "-",
        "descriptionUrl": "https://www.youtube.com/watch?v=Qk2UGlFNKPE",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "46",
        "date": "Saturday, February 15, 2020",
        "time": "9:00:00 PM",
        "dateTime": "2020-02-16 21:00:00",
        "blockName": "Chrome DevTools",
        "name": "Friday Live Coding. Part 5",
        "timeToComplete": "3,5h",
        "description": "вебинар Виктории Ворожун\r\nVanilla JS. DOM.",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/ouZnGUefneQ",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "47",
        "date": "Sunday, February 16, 2020",
        "time": "10:00:00 PM",
        "dateTime": "2020-02-17 22:00:00",
        "blockName": "Chrome DevTools",
        "name": "Preprocessors. SASS",
        "timeToComplete": "2h",
        "description": "вебинар Виктории Ворожун",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/JO8DvVZbxDw",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "48",
        "date": "Monday, February 17, 2020",
        "time": "11:00:00 PM",
        "dateTime": "2020-02-18 23:00:00",
        "blockName": "Chrome DevTools",
        "name": "Основы Sass",
        "timeToComplete": "1h",
        "description": "Доступное объяснение особенностей sass с примерами",
        "comment": "-",
        "descriptionUrl": "https://sass-scss.ru/guide/",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "49",
        "date": "Tuesday, February 18, 2020",
        "time": "12:00:00 AM",
        "dateTime": "2020-02-20 0:00:00",
        "blockName": "Chrome DevTools",
        "name": "JavaScript для верстальщика",
        "timeToComplete": "1h",
        "description": "Основы JavaScript достаточные для добавления логики на сайт",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/js-for-frontend.md",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "50",
        "date": "Wednesday, February 19, 2020",
        "time": "1:00:00 AM",
        "dateTime": "2020-02-21 1:00:00",
        "blockName": "CSS positioning and layout (Grid)",
        "name": "Вёрстка на Grid в CSS",
        "timeToComplete": "0.5h",
        "description": "Студент знает особенности вёрстки на гридах",
        "comment": "-",
        "descriptionUrl": "https://medium.com/@stasonmars/%D0%B2%D0%B5%CC%88%D1%80%D1%81%D1%82%D0%BA%D0%B0-%D0%BD%D0%B0-grid-%D0%B2-css-%D0%BF%D0%BE%D0%BB%D0%BD%D0%BE%D0%B5-%D1%80%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE-%D0%B8-%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D0%BE%D1%87%D0%BD%D0%B8%D0%BA-220508316f8b",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "51",
        "date": "Thursday, February 20, 2020",
        "time": "2:00:00 AM",
        "dateTime": "2020-02-22 2:00:00",
        "blockName": "CSS positioning and layout (Grid)",
        "name": "Grid ( видео курс)",
        "timeToComplete": "1,5h",
        "description": "Простым языком про грид, с примерами",
        "comment": "-",
        "descriptionUrl": "https://www.youtube.com/watch?v=LHW_M9mf4Is&list=PLNkWIWHIRwMHlq6yOP65F_rNH5wID1U21&index=1",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "52",
        "date": "Friday, February 21, 2020",
        "time": "3:00:00 AM",
        "dateTime": "2020-02-23 3:00:00",
        "blockName": "Практика",
        "name": "Изучение гридов посредством игры",
        "timeToComplete": "1h",
        "description": "Студент использует гриды для решения поставленных задач",
        "comment": "-",
        "descriptionUrl": "https://cssgridgarden.com/#ru",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "53",
        "date": "Saturday, February 22, 2020",
        "time": "4:00:00 AM",
        "dateTime": "2020-02-24 4:00:00",
        "blockName": "Практика",
        "name": "simple-singolo",
        "timeToComplete": "40h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/simple-singolo.md",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "54",
        "date": "Sunday, February 23, 2020",
        "time": "5:00:00 AM",
        "dateTime": "2020-02-25 5:00:00",
        "blockName": "JS Basic",
        "name": "Введение в JavaScript",
        "timeToComplete": "0.5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/intro",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "55",
        "date": "Monday, February 24, 2020",
        "time": "6:00:00 AM",
        "dateTime": "2020-02-26 6:00:00",
        "blockName": "JS Basic",
        "name": "Привет, мир!",
        "timeToComplete": "0.5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/hello-world",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "56",
        "date": "Tuesday, February 25, 2020",
        "time": "7:00:00 AM",
        "dateTime": "2020-02-27 7:00:00",
        "blockName": "JS Basic",
        "name": "Переменные (обязательно выполнять задание в конце главы)",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/variables",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "57",
        "date": "Wednesday, February 26, 2020",
        "time": "8:00:00 AM",
        "dateTime": "2020-02-28 8:00:00",
        "blockName": "JS Basic",
        "name": "Основы JavaScript",
        "timeToComplete": "10h",
        "description": "плейлист от Sorax - 35 видео по JavaScript",
        "comment": "-",
        "descriptionUrl": "https://www.youtube.com/playlist?list=PL363QX7S8MfSxcHzvkNEqMYbOyhLeWwem",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "58",
        "date": "Thursday, February 27, 2020",
        "time": "9:00:00 AM",
        "dateTime": "2020-02-29 9:00:00",
        "blockName": "Data types",
        "name": "Видео лекция JS Data types. Смотреть до массивов, те 1ч 5 мин",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://www.youtube.com/watch?v=w420Ullz2cw&list=PLe--kalBDwji8WXKVjhON39X4v_Uj6T_R&index=4",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "59",
        "date": "Friday, February 28, 2020",
        "time": "10:00:00 AM",
        "dateTime": "2020-03-01 10:00:00",
        "blockName": "Data types",
        "name": "Типы данных",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/types",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "60",
        "date": "Saturday, February 29, 2020",
        "time": "11:00:00 AM",
        "dateTime": "2020-03-02 11:00:00",
        "blockName": "Data types",
        "name": "Вы не знаете JS: типы данных и значения",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://medium.com/@Dimetrio89/%D0%B2%D1%8B-%D0%BD%D0%B5-%D0%B7%D0%BD%D0%B0%D0%B5%D1%82%D0%B5-js-%D1%82%D0%B8%D0%BF%D1%8B-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85-%D0%B8-%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D1%8F-f95a605de82",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "61",
        "date": "Sunday, March 1, 2020",
        "time": "12:00:00 PM",
        "dateTime": "2020-03-03 12:00:00",
        "blockName": "Data types",
        "name": "Преобразование типов",
        "timeToComplete": "0,5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/type-conversions",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "62",
        "date": "Monday, March 2, 2020",
        "time": "1:00:00 PM",
        "dateTime": "2020-03-04 13:00:00",
        "blockName": "Data types",
        "name": "Операторы",
        "timeToComplete": "0,5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/operators",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "63",
        "date": "Tuesday, March 3, 2020",
        "time": "2:00:00 PM",
        "dateTime": "2020-03-05 14:00:00",
        "blockName": "Condition, loop",
        "name": "Операторы сравнения",
        "timeToComplete": "0,5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/comparison",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "64",
        "date": "Wednesday, March 4, 2020",
        "time": "3:00:00 PM",
        "dateTime": "2020-03-06 15:00:00",
        "blockName": "Condition, loop",
        "name": "Условные операторы: if, '?'",
        "timeToComplete": "0,5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/ifelse",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "65",
        "date": "Thursday, March 5, 2020",
        "time": "4:00:00 PM",
        "dateTime": "2020-03-07 16:00:00",
        "blockName": "Condition, loop",
        "name": "Логические операторы",
        "timeToComplete": "0,5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/logical-operators",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "66",
        "date": "Friday, March 6, 2020",
        "time": "5:00:00 PM",
        "dateTime": "2020-03-08 17:00:00",
        "blockName": "Condition, loop",
        "name": "Циклы while и for",
        "timeToComplete": "0,5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/while-for",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "67",
        "date": "Saturday, March 7, 2020",
        "time": "6:00:00 PM",
        "dateTime": "2020-03-09 18:00:00",
        "blockName": "Condition, loop",
        "name": "Конструкция \"switch\"",
        "timeToComplete": "0,5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/switch",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "68",
        "date": "Sunday, March 8, 2020",
        "time": "7:00:00 PM",
        "dateTime": "2020-03-10 19:00:00",
        "blockName": "Практика",
        "name": "Codewars Basic",
        "timeToComplete": "10h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/codewars-basic.md",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "69",
        "date": "Monday, March 9, 2020",
        "time": "8:00:00 PM",
        "dateTime": "2020-03-11 20:00:00",
        "blockName": "Практика",
        "name": "Task 1. Calculator",
        "timeToComplete": "10h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/projects.md#task-1-calculator",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "70",
        "date": "Tuesday, March 10, 2020",
        "time": "9:00:00 PM",
        "dateTime": "2020-03-12 21:00:00",
        "blockName": "Arrays",
        "name": "Видео лекция JS Data types. Смотрим начиная с массивов",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/w420Ullz2cw?t=3859",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "71",
        "date": "Wednesday, March 11, 2020",
        "time": "10:00:00 PM",
        "dateTime": "2020-03-13 22:00:00",
        "blockName": "Object",
        "name": "Объекты",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/object",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "72",
        "date": "Thursday, March 12, 2020",
        "time": "11:00:00 PM",
        "dateTime": "2020-03-14 23:00:00",
        "blockName": "Object",
        "name": "Работа с объектами",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Working_with_Objects",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "73",
        "date": "Friday, March 13, 2020",
        "time": "12:00:00 AM",
        "dateTime": "2020-03-16 0:00:00",
        "blockName": "Object",
        "name": "Основы javascript",
        "timeToComplete": "8h",
        "description": "Отличный плейлист от loftblog 24 видео",
        "comment": "-",
        "descriptionUrl": "https://www.youtube.com/playlist?list=PLY4rE9dstrJymG1GyPLgOKsJNq9r-p6pX",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "74",
        "date": "Saturday, March 14, 2020",
        "time": "1:00:00 AM",
        "dateTime": "2020-03-17 1:00:00",
        "blockName": "Функции",
        "name": "Функции",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/function-basics",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "75",
        "date": "Sunday, March 15, 2020",
        "time": "2:00:00 AM",
        "dateTime": "2020-03-18 2:00:00",
        "blockName": "Функции",
        "name": "Function Expression",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/function-expressions",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "76",
        "date": "Monday, March 16, 2020",
        "time": "3:00:00 AM",
        "dateTime": "2020-03-19 3:00:00",
        "blockName": "Функции",
        "name": "Функции-стрелки, основы",
        "timeToComplete": "0,5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/arrow-functions-basics",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "77",
        "date": "Tuesday, March 17, 2020",
        "time": "4:00:00 AM",
        "dateTime": "2020-03-20 4:00:00",
        "blockName": "Функции",
        "name": "Видео лекция",
        "timeToComplete": "2,5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://www.youtube.com/watch?v=fShrn50Fkhw&list=PLe--kalBDwji8WXKVjhON39X4v_Uj6T_R&index=6",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "78",
        "date": "Wednesday, March 18, 2020",
        "time": "5:00:00 AM",
        "dateTime": "2020-03-21 5:00:00",
        "blockName": "Data mapping /Basic operations",
        "name": "Методы у примитивов",
        "timeToComplete": "0,5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/primitives-methods",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "79",
        "date": "Thursday, March 19, 2020",
        "time": "6:00:00 AM",
        "dateTime": "2020-03-22 6:00:00",
        "blockName": "Data mapping /Basic operations",
        "name": "Числа",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/number",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "80",
        "date": "Friday, March 20, 2020",
        "time": "7:00:00 AM",
        "dateTime": "2020-03-23 7:00:00",
        "blockName": "Data mapping /Basic operations",
        "name": "Строки",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/string",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "81",
        "date": "Saturday, March 21, 2020",
        "time": "8:00:00 AM",
        "dateTime": "2020-03-24 8:00:00",
        "blockName": "Data mapping /Basic operations",
        "name": "Массивы",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/array",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "82",
        "date": "Sunday, March 22, 2020",
        "time": "9:00:00 AM",
        "dateTime": "2020-03-25 9:00:00",
        "blockName": "Data mapping /Basic operations",
        "name": "Методы массивов",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/array-methods",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "83",
        "date": "Monday, March 23, 2020",
        "time": "10:00:00 AM",
        "dateTime": "2020-03-26 10:00:00",
        "blockName": "Data mapping /Basic operations",
        "name": "Object.keys, values, entries",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/keys-values-entries",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "84",
        "date": "Tuesday, March 24, 2020",
        "time": "11:00:00 AM",
        "dateTime": "2020-03-27 11:00:00",
        "blockName": "Data mapping /Basic operations",
        "name": "Деструктурирующее присваивание",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/destructuring-assignment",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "85",
        "date": "Wednesday, March 25, 2020",
        "time": "12:00:00 PM",
        "dateTime": "2020-03-28 12:00:00",
        "blockName": "Практика ",
        "name": "Task 2. Dynamic Landing Page",
        "timeToComplete": "6h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/projects.md#task-2-dynamic-landing-page",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "86",
        "date": "Thursday, March 26, 2020",
        "time": "1:00:00 PM",
        "dateTime": "2020-03-29 13:00:00",
        "blockName": "Практика ",
        "name": "Task 3. Meditation App",
        "timeToComplete": "4h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/projects.md#task-3-meditation-app",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "87",
        "date": "Friday, March 27, 2020",
        "time": "2:00:00 PM",
        "dateTime": "2020-03-30 14:00:00",
        "blockName": "Практика ",
        "name": "Task 4. Drum Kit",
        "timeToComplete": "4h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/projects.md#task-4-drum-kit",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "88",
        "date": "Saturday, March 28, 2020",
        "time": "3:00:00 PM",
        "dateTime": "2020-03-31 15:00:00",
        "blockName": "Практика ",
        "name": "Task 5. CSS Variables and JS",
        "timeToComplete": "4h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/projects.md#task-5-css-variables-and-js",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "89",
        "date": "Sunday, March 29, 2020",
        "time": "4:00:00 PM",
        "dateTime": "2020-04-01 16:00:00",
        "blockName": "Практика ",
        "name": "Task 6. Flex Panel Gallery",
        "timeToComplete": "2h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/projects.md#task-6-flex-panel-gallery",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "90",
        "date": "Monday, March 30, 2020",
        "time": "5:00:00 PM",
        "dateTime": "2020-04-02 17:00:00",
        "blockName": "Дата и время",
        "name": "Дата и время",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/date",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "91",
        "date": "Tuesday, March 31, 2020",
        "time": "6:00:00 PM",
        "dateTime": "2020-04-03 18:00:00",
        "blockName": "DOM, elements",
        "name": "Браузерное окружение, спецификации",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/browser-environment",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "92",
        "date": "Wednesday, April 1, 2020",
        "time": "7:00:00 PM",
        "dateTime": "2020-04-04 19:00:00",
        "blockName": "DOM, elements",
        "name": "DOM-дерево",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/dom-nodes",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "93",
        "date": "Thursday, April 2, 2020",
        "time": "8:00:00 PM",
        "dateTime": "2020-04-05 20:00:00",
        "blockName": "DOM, elements",
        "name": "Навигация по DOM-элементам",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/dom-navigation",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "94",
        "date": "Friday, April 3, 2020",
        "time": "9:00:00 PM",
        "dateTime": "2020-04-06 21:00:00",
        "blockName": "DOM, elements",
        "name": "Поиск: getElement*, querySelector*",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/searching-elements-dom",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "95",
        "date": "Saturday, April 4, 2020",
        "time": "10:00:00 PM",
        "dateTime": "2020-04-07 22:00:00",
        "blockName": "DOM, elements",
        "name": "Свойства узлов: тип, тег и содержимое",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/basic-dom-node-properties",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "96",
        "date": "Sunday, April 5, 2020",
        "time": "11:00:00 PM",
        "dateTime": "2020-04-08 23:00:00",
        "blockName": "DOM, elements",
        "name": "Атрибуты и свойства",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/dom-attributes-and-properties",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "97",
        "date": "Monday, April 6, 2020",
        "time": "12:00:00 AM",
        "dateTime": "2020-04-10 0:00:00",
        "blockName": "DOM, elements",
        "name": "Изменение документа",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/modifying-document",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "98",
        "date": "Tuesday, April 7, 2020",
        "time": "1:00:00 AM",
        "dateTime": "2020-04-11 1:00:00",
        "blockName": "DOM, elements",
        "name": "Стили и классы",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/styles-and-classes",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "99",
        "date": "Wednesday, April 8, 2020",
        "time": "2:00:00 AM",
        "dateTime": "2020-04-12 2:00:00",
        "blockName": "DOM, elements",
        "name": "Размеры и прокрутка элементов",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/size-and-scroll",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "100",
        "date": "Thursday, April 9, 2020",
        "time": "3:00:00 AM",
        "dateTime": "2020-04-13 3:00:00",
        "blockName": "DOM, elements",
        "name": "Размеры и прокрутка окна",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/size-and-scroll-window",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "101",
        "date": "Friday, April 10, 2020",
        "time": "4:00:00 AM",
        "dateTime": "2020-04-14 4:00:00",
        "blockName": "DOM, elements",
        "name": "Координаты",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/coordinates",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "102",
        "date": "Saturday, April 11, 2020",
        "time": "5:00:00 AM",
        "dateTime": "2020-04-15 5:00:00",
        "blockName": "Browser events, other events",
        "name": "Введение в браузерные события",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/introduction-browser-events",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "103",
        "date": "Sunday, April 12, 2020",
        "time": "6:00:00 AM",
        "dateTime": "2020-04-16 6:00:00",
        "blockName": "Browser events, other events",
        "name": "Всплытие и погружение",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/bubbling-and-capturing",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "104",
        "date": "Monday, April 13, 2020",
        "time": "7:00:00 AM",
        "dateTime": "2020-04-17 7:00:00",
        "blockName": "Browser events, other events",
        "name": "Делегирование событий",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/event-delegation",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "105",
        "date": "Tuesday, April 14, 2020",
        "time": "8:00:00 AM",
        "dateTime": "2020-04-18 8:00:00",
        "blockName": "Browser events, other events",
        "name": "Действия браузера по умолчанию",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/default-browser-action",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "106",
        "date": "Wednesday, April 15, 2020",
        "time": "9:00:00 AM",
        "dateTime": "2020-04-19 9:00:00",
        "blockName": "Browser events, other events",
        "name": "Генерация пользовательских событий",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/dispatch-events",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "107",
        "date": "Thursday, April 16, 2020",
        "time": "10:00:00 AM",
        "dateTime": "2020-04-20 10:00:00",
        "blockName": "Browser events, other events",
        "name": "Основы событий мыши",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/mouse-events-basics",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "108",
        "date": "Friday, April 17, 2020",
        "time": "11:00:00 AM",
        "dateTime": "2020-04-21 11:00:00",
        "blockName": "Browser events, other events",
        "name": "Движение мыши: mouseover/out, mouseenter/leave",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/mousemove-mouseover-mouseout-mouseenter-mouseleave",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "109",
        "date": "Saturday, April 18, 2020",
        "time": "12:00:00 PM",
        "dateTime": "2020-04-22 12:00:00",
        "blockName": "Browser events, other events",
        "name": "Drag'n'Drop с событиями мыши",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/mouse-drag-and-drop",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "110",
        "date": "Sunday, April 19, 2020",
        "time": "1:00:00 PM",
        "dateTime": "2020-04-23 13:00:00",
        "blockName": "Browser events, other events",
        "name": "Понимание javascript - работа с DOM",
        "timeToComplete": "2h",
        "description": "Вебинары Дмитрия Лаврика, направленные на понимание JavaScript и его особенностей",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/-2WiaSvOj78",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "111",
        "date": "Monday, April 20, 2020",
        "time": "2:00:00 PM",
        "dateTime": "2020-04-24 14:00:00",
        "blockName": "Browser events, other events",
        "name": "Понимание javascript - работа с DOM",
        "timeToComplete": "2h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/-2WiaSvOj78",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "112",
        "date": "Tuesday, April 21, 2020",
        "time": "3:00:00 PM",
        "dateTime": "2020-04-25 15:00:00",
        "blockName": "Browser events, other events",
        "name": "Javascript. Стандарт ES6. Смысл, основные фишки и подвохи",
        "timeToComplete": "2h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/Spme1IW1ejg",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "113",
        "date": "Wednesday, April 22, 2020",
        "time": "4:00:00 PM",
        "dateTime": "2020-04-26 16:00:00",
        "blockName": "Browser events, other events",
        "name": "Внутренний мир javascript: объекты и прототипы",
        "timeToComplete": "2h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/zWjT_2hFkMw",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "114",
        "date": "Thursday, April 23, 2020",
        "time": "5:00:00 PM",
        "dateTime": "2020-04-27 17:00:00",
        "blockName": "Browser events, other events",
        "name": "Javascipt и анимации - взаимодействие с CSS",
        "timeToComplete": "2h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/0TLnIQbk5qo",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "115",
        "date": "Friday, April 24, 2020",
        "time": "6:00:00 PM",
        "dateTime": "2020-04-28 18:00:00",
        "blockName": "Webpack",
        "name": "Webpack 4 - простая сборка проекта",
        "timeToComplete": "2h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/MRlBKfGktwI",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "116",
        "date": "Saturday, April 25, 2020",
        "time": "7:00:00 PM",
        "dateTime": "2020-04-29 19:00:00",
        "blockName": "Webpack",
        "name": "Webpack. Полный курс 2020",
        "timeToComplete": "3h",
        "description": "Курс от Владилена Минина по webpack считается одним из лучших",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/eSaF8NXeNsA",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "117",
        "date": "Sunday, April 26, 2020",
        "time": "8:00:00 PM",
        "dateTime": "2020-04-30 20:00:00",
        "blockName": "Практика",
        "name": "Codewars Basic-1",
        "timeToComplete": "10h ",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/codewars-basic-1.md",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "118",
        "date": "Monday, April 27, 2020",
        "time": "9:00:00 PM",
        "dateTime": "2020-05-01 21:00:00",
        "blockName": "Практика",
        "name": "Task 7. Fun with HTML5 Canvas",
        "timeToComplete": "8h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/projects.md#task-7-fun-with-html5-canvas",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "119",
        "date": "Tuesday, April 28, 2020",
        "time": "10:00:00 PM",
        "dateTime": "2020-05-02 22:00:00",
        "blockName": "Практика",
        "name": "Task 8. Custom Video Player",
        "timeToComplete": "4h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/projects.md#task-8-custom-video-player",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "120",
        "date": "Wednesday, April 29, 2020",
        "time": "11:00:00 PM",
        "dateTime": "2020-05-03 23:00:00",
        "blockName": "Практика",
        "name": "Task 9. Video Speed Controller",
        "timeToComplete": "2h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/projects.md#task-9-video-speed-controller",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "121",
        "date": "Thursday, April 30, 2020",
        "time": "12:00:00 AM",
        "dateTime": "2020-05-05 0:00:00",
        "blockName": "Практика",
        "name": "Task 10. Whack-A-Mole",
        "timeToComplete": "8h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/projects.md#task-10-whack-a-mole",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "122",
        "date": "Friday, May 1, 2020",
        "time": "1:00:00 AM",
        "dateTime": "2020-05-06 1:00:00",
        "blockName": "Практика",
        "name": "Task 11. Virtual Keyboard",
        "timeToComplete": "8h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/projects.md#task-11-virtual-keyboard",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "123",
        "date": "Saturday, May 2, 2020",
        "time": "2:00:00 AM",
        "dateTime": "2020-05-07 2:00:00",
        "blockName": "This. Scope. Closure",
        "name": "Сложный JavaScript простым языком",
        "timeToComplete": "20h",
        "description": "плейлист, prototype, call, bind, this, замыкания, event loop, , асинхронность, промисы, классы и т д",
        "comment": "-",
        "descriptionUrl": "https://www.youtube.com/watch?v=aQkgUUmUJy4&list=PLqKQF2ojwm3l4oPjsB9chrJmlhZ-zOzWT",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "124",
        "date": "Sunday, May 3, 2020",
        "time": "3:00:00 AM",
        "dateTime": "2020-05-08 3:00:00",
        "blockName": "This. Scope. Closure",
        "name": "Контексты исполнения.",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "http://dmitrysoshnikov.com/ecmascript/ru-chapter-1-execution-contexts/",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "125",
        "date": "Monday, May 4, 2020",
        "time": "4:00:00 AM",
        "dateTime": "2020-05-09 4:00:00",
        "blockName": "This. Scope. Closure",
        "name": "Объект переменных.",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "http://dmitrysoshnikov.com/ecmascript/ru-chapter-2-variable-object/",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "126",
        "date": "Tuesday, May 5, 2020",
        "time": "5:00:00 AM",
        "dateTime": "2020-05-10 5:00:00",
        "blockName": "This. Scope. Closure",
        "name": "This.",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "http://dmitrysoshnikov.com/ecmascript/ru-chapter-3-this/",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "127",
        "date": "Wednesday, May 6, 2020",
        "time": "6:00:00 AM",
        "dateTime": "2020-05-11 6:00:00",
        "blockName": "This. Scope. Closure",
        "name": "Цепь областей видимости.",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "http://dmitrysoshnikov.com/ecmascript/ru-chapter-4-scope-chain/",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "128",
        "date": "Thursday, May 7, 2020",
        "time": "7:00:00 AM",
        "dateTime": "2020-05-12 7:00:00",
        "blockName": "This. Scope. Closure",
        "name": "Функции.",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "http://dmitrysoshnikov.com/ecmascript/ru-chapter-5-functions/",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "129",
        "date": "Friday, May 8, 2020",
        "time": "8:00:00 AM",
        "dateTime": "2020-05-13 8:00:00",
        "blockName": "This. Scope. Closure",
        "name": "Замыкания.",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "http://dmitrysoshnikov.com/ecmascript/ru-chapter-6-closures/",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "130",
        "date": "Saturday, May 9, 2020",
        "time": "9:00:00 AM",
        "dateTime": "2020-05-14 9:00:00",
        "blockName": "OOP",
        "name": "[J]u[S]t prototype this",
        "timeToComplete": "1.5h",
        "description": "Отличная видеолекция по JavaScript. У автора определённо талант рассказывать понятно и доступно о сложных вещах.",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/5l01s6Vkqp0",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "131",
        "date": "Sunday, May 10, 2020",
        "time": "10:00:00 AM",
        "dateTime": "2020-05-15 10:00:00",
        "blockName": "Inheritance",
        "name": "Класс: базовый синтаксис",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/class",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "132",
        "date": "Monday, May 11, 2020",
        "time": "11:00:00 AM",
        "dateTime": "2020-05-16 11:00:00",
        "blockName": "Inheritance",
        "name": "Наследование классов",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/class-inheritance",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "133",
        "date": "Tuesday, May 12, 2020",
        "time": "12:00:00 PM",
        "dateTime": "2020-05-17 12:00:00",
        "blockName": "Inheritance",
        "name": "Статические свойства и методы",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/static-properties-methods",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "134",
        "date": "Wednesday, May 13, 2020",
        "time": "1:00:00 PM",
        "dateTime": "2020-05-18 13:00:00",
        "blockName": "Inheritance",
        "name": "Приватные и защищённые методы и свойства",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/private-protected-properties-methods",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "135",
        "date": "Thursday, May 14, 2020",
        "time": "2:00:00 PM",
        "dateTime": "2020-05-19 14:00:00",
        "blockName": "Inheritance",
        "name": "Расширение встроенных классов",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/extend-natives",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "136",
        "date": "Friday, May 15, 2020",
        "time": "3:00:00 PM",
        "dateTime": "2020-05-20 15:00:00",
        "blockName": "Inheritance",
        "name": "Проверка класса: \"instanceof\"",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/instanceof",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "137",
        "date": "Saturday, May 16, 2020",
        "time": "4:00:00 PM",
        "dateTime": "2020-05-21 16:00:00",
        "blockName": "Inheritance",
        "name": "Примеси",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://learn.javascript.ru/mixins",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "138",
        "date": "Sunday, May 17, 2020",
        "time": "5:00:00 PM",
        "dateTime": "2020-05-22 17:00:00",
        "blockName": "ES6 + features",
        "name": "EcmaScript - Полный курс (ES6, ES7, ES8)",
        "timeToComplete": "3.5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://www.youtube.com/watch?v=Ti2Q4sQkNdU",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "139",
        "date": "Monday, May 18, 2020",
        "time": "6:00:00 PM",
        "dateTime": "2020-05-23 18:00:00",
        "blockName": "ES6 + features",
        "name": "ES6 по-человечески",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://habr.com/ru/post/305900/",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "140",
        "date": "Tuesday, May 19, 2020",
        "time": "7:00:00 PM",
        "dateTime": "2020-05-24 19:00:00",
        "blockName": "ES6 + features",
        "name": "Что нового в JavaScript 2020?",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/7TpAN4FISeI",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "141",
        "date": "Wednesday, May 20, 2020",
        "time": "8:00:00 PM",
        "dateTime": "2020-05-25 20:00:00",
        "blockName": "Практика",
        "name": "Raindrops",
        "timeToComplete": "40h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/raindrops.md",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "142",
        "date": "Thursday, May 21, 2020",
        "time": "9:00:00 PM",
        "dateTime": "2020-05-26 21:00:00",
        "blockName": "Async programming",
        "name": "Асинхронность в JavaScript",
        "timeToComplete": "2.5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/Ih6Q7ka2eSQ",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "143",
        "date": "Friday, May 22, 2020",
        "time": "10:00:00 PM",
        "dateTime": "2020-05-27 22:00:00",
        "blockName": "Async programming",
        "name": "Полное понимание синхронного и асинхронного JavaScript с Async/Await",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://medium.com/@stasonmars/%D0%BF%D0%BE%D0%BB%D0%BD%D0%BE%D0%B5-%D0%BF%D0%BE%D0%BD%D0%B8%D0%BC%D0%B0%D0%BD%D0%B8%D0%B5-%D1%81%D0%B8%D0%BD%D1%85%D1%80%D0%BE%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%B8-%D0%B0%D1%81%D0%B8%D0%BD%D1%85%D1%80%D0%BE%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-javascript-%D1%81-async-await-ba5f47f4436",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "144",
        "date": "Saturday, May 23, 2020",
        "time": "11:00:00 PM",
        "dateTime": "2020-05-28 23:00:00",
        "blockName": "Async programming",
        "name": "Про цикл событий в JavaScript или \"как на самом деле работает асинхронность\"?",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/8cV4ZvHXQL4",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "145",
        "date": "Sunday, May 24, 2020",
        "time": "12:00:00 AM",
        "dateTime": "2020-05-30 0:00:00",
        "blockName": "Async programming",
        "name": "Асинхронные запросы. Использование Fetch",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://developer.mozilla.org/ru/docs/Web/API/Fetch_API/Using_Fetch",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "146",
        "date": "Monday, May 25, 2020",
        "time": "1:00:00 AM",
        "dateTime": "2020-05-31 1:00:00",
        "blockName": "Async programming",
        "name": "Асинхронные функции (async/await)",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/5kAPExqSZ1I",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "147",
        "date": "Tuesday, May 26, 2020",
        "time": "2:00:00 AM",
        "dateTime": "2020-06-01 2:00:00",
        "blockName": "Async programming",
        "name": "JavaScript Fetch API and using Async/Await",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://dev.to/shoupn/javascript-fetch-api-and-using-asyncawait-47mp",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "148",
        "date": "Wednesday, May 27, 2020",
        "time": "3:00:00 AM",
        "dateTime": "2020-06-02 3:00:00",
        "blockName": "RESTful API Style",
        "name": "Разбираемся с REST и RESTful API",
        "timeToComplete": "1h",
        "description": "Студент знает\r\n что из себя представляют REST и RESTful API\r\n- принципы REST\r\n-  методы запроса HTTP, \r\n- какими бывают и что означают коды ответа",
        "comment": "-",
        "descriptionUrl": "https://code.tutsplus.com/ru/tutorials/code-your-first-api-with-nodejs-and-express-understanding-rest-apis--cms-31697",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "149",
        "date": "Thursday, May 28, 2020",
        "time": "4:00:00 AM",
        "dateTime": "2020-06-03 4:00:00",
        "blockName": "RESTful API Style",
        "name": "REST: простым языком",
        "timeToComplete": "1h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://medium.com/@andr.ivas12/rest-%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%8B%D0%BC-%D1%8F%D0%B7%D1%8B%D0%BA%D0%BE%D0%BC-90a0bca0bc78",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "150",
        "date": "Friday, May 29, 2020",
        "time": "5:00:00 AM",
        "dateTime": "2020-06-04 5:00:00",
        "blockName": "Практика",
        "name": "Codewars Basic-2",
        "timeToComplete": "10h ",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/codewars-basic-2.md",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "151",
        "date": "Saturday, May 30, 2020",
        "time": "6:00:00 AM",
        "dateTime": "2020-06-05 6:00:00",
        "blockName": "Практика",
        "name": "Task Fancy-weather",
        "timeToComplete": "60h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/fancy-weather.md",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "152",
        "date": "Sunday, May 31, 2020",
        "time": "7:00:00 AM",
        "dateTime": "2020-06-06 7:00:00",
        "blockName": "HTTP/ HTTPS",
        "name": "Разница между HTTP и HTTPS",
        "timeToComplete": "0.5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://hostiq.ua/wiki/http-https/",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "153",
        "date": "Monday, June 1, 2020",
        "time": "8:00:00 AM",
        "dateTime": "2020-06-07 8:00:00",
        "blockName": "WebSocket",
        "name": "Знакомство с WebSocket",
        "timeToComplete": "0.5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/DKOaL94VyFY",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "154",
        "date": "Tuesday, June 2, 2020",
        "time": "9:00:00 AM",
        "dateTime": "2020-06-08 9:00:00",
        "blockName": "WebSocket",
        "name": "https://www.websocket.org/echo.html",
        "timeToComplete": "0.5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://www.websocket.org/echo.html",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "155",
        "date": "Wednesday, June 3, 2020",
        "time": "10:00:00 AM",
        "dateTime": "2020-06-09 10:00:00",
        "blockName": "WebSocket",
        "name": "WebSockets",
        "timeToComplete": "1.5h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://youtu.be/rpyk9JGAPZs",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "156",
        "date": "Thursday, June 4, 2020",
        "time": "11:00:00 AM",
        "dateTime": "2020-06-10 11:00:00",
        "blockName": "WebSocket",
        "name": "Практика JavaScript",
        "timeToComplete": "6h",
        "description": "Плейлист из 5 видео от Владилена Минина с примерами решения практических задач по JavaScript",
        "comment": "-",
        "descriptionUrl": "https://www.youtube.com/playlist?list=PLqKQF2ojwm3n-ufn3E-l6Y0VxDrj3hM5M",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "157",
        "date": "Friday, June 5, 2020",
        "time": "12:00:00 PM",
        "dateTime": "2020-06-11 12:00:00",
        "blockName": "Практика",
        "name": "Task 12. Chat on socket.io",
        "timeToComplete": "4h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/stage-0/projects.md#task-12-chat-on-socketio",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "158",
        "date": "Saturday, June 6, 2020",
        "time": "1:00:00 PM",
        "dateTime": "2020-06-12 13:00:00",
        "blockName": "Практика",
        "name": "Portfolio",
        "timeToComplete": "20h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://github.com/rolling-scopes-school/tasks/blob/master/tasks/Portfolio.md",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "159",
        "date": "Sunday, June 7, 2020",
        "time": "2:00:00 PM",
        "dateTime": "2020-06-13 14:00:00",
        "blockName": "Interview",
        "name": "Список вопросов по JavaScript",
        "timeToComplete": "10h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://github.com/lydiahallie/javascript-questions/blob/master/ru-RU/README.md",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    },
    {
        "id": "160",
        "date": "Monday, June 8, 2020",
        "time": "3:00:00 PM",
        "dateTime": "2020-06-14 15:00:00",
        "blockName": "Interview",
        "name": "Подготовка к собеседованию",
        "timeToComplete": "30h",
        "description": "-",
        "comment": "-",
        "descriptionUrl": "https://github.com/irinainina/rsschool-materials#%D0%BF%D0%BE%D0%B4%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D0%BA%D0%B0-%D0%BA-%D1%81%D0%BE%D0%B1%D0%B5%D1%81%D0%B5%D0%B4%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8E",
        "timeZone": "UTC +3 MSK Minsk",
        "place": "online",
        "type": "Self education"
    }
        ]